name: Deploy Cost Guardian

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::894943009636:role/cost-guardian-github-role
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infra/envs/dev init

      - name: Terraform Validate
        run: terraform -chdir=infra/envs/dev validate

      - name: Terraform Plan
        run: terraform -chdir=infra/envs/dev plan input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform -chdir=infra/envs/dev apply -auto-approve
